name: Python

on:
  push:
    branches:
      - master
    
    tags:
      - v*
  
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Type-check
      run: |
        mypy .

    - name: Test
      run: |
        python -m unittest -v

    - name: Check formatting
      run: |
        black --check .
